// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
}
namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Input
    {
        
        static SteamVR_Input()
        {
            SteamVR_Input.PreInitialize();
        }
        
        public static void PreInitialize()
        {
            SteamVR_Input.StartPreInitActionSets();
            SteamVR_Input.InitializeActionSetDictionaries();
            SteamVR_Input.PreInitActions();
            SteamVR_Input.InitializeActionArrays();
            SteamVR_Input.InitializeActionDictionaries();
            SteamVR_Input.FinishPreInitActionSets();
        }
    }
}
