// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Input
    {
        
        private static SteamVR_Action_Boolean p___actions_default_in_GrabGrip;
        
        private static SteamVR_Action_Pose p___actions_default_in_Pose;
        
        private static SteamVR_Action_Skeleton p___actions_default_in_SkeletonLeftHand;
        
        private static SteamVR_Action_Skeleton p___actions_default_in_SkeletonRightHand;
        
        private static SteamVR_Action_Boolean p___actions_default_in_PinchGrip;
        
        private static SteamVR_Action_Vibration p___actions_default_out_Haptic;
        
        private static SteamVR_Action_Boolean p___actions_HandPoseAssist_in_TrackpadTouch;
        
        private static SteamVR_Action_Boolean p___actions_HandPoseAssist_in_AButtonTouch;
        
        private static SteamVR_Action_Boolean p___actions_HandPoseAssist_in_BButtonTouch;
        
        private static SteamVR_Action_Boolean p___actions_HandPoseAssist_in_TriggerTouch;
        
        private static SteamVR_Action_Single p___actions_HandPoseAssist_in_TriggerPull;
        
        public static SteamVR_Action_Boolean __actions_default_in_GrabGrip
        {
            get
            {
                return Valve.VR.SteamVR_Input.p___actions_default_in_GrabGrip.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose __actions_default_in_Pose
        {
            get
            {
                return Valve.VR.SteamVR_Input.p___actions_default_in_Pose.GetCopy <SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Skeleton __actions_default_in_SkeletonLeftHand
        {
            get
            {
                return Valve.VR.SteamVR_Input.p___actions_default_in_SkeletonLeftHand.GetCopy <SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Skeleton __actions_default_in_SkeletonRightHand
        {
            get
            {
                return Valve.VR.SteamVR_Input.p___actions_default_in_SkeletonRightHand.GetCopy <SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Boolean __actions_default_in_PinchGrip
        {
            get
            {
                return Valve.VR.SteamVR_Input.p___actions_default_in_PinchGrip.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vibration __actions_default_out_Haptic
        {
            get
            {
                return Valve.VR.SteamVR_Input.p___actions_default_out_Haptic.GetCopy <SteamVR_Action_Vibration>();
            }
        }
        
        public static SteamVR_Action_Boolean __actions_HandPoseAssist_in_TrackpadTouch
        {
            get
            {
                return Valve.VR.SteamVR_Input.p___actions_HandPoseAssist_in_TrackpadTouch.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean __actions_HandPoseAssist_in_AButtonTouch
        {
            get
            {
                return Valve.VR.SteamVR_Input.p___actions_HandPoseAssist_in_AButtonTouch.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean __actions_HandPoseAssist_in_BButtonTouch
        {
            get
            {
                return Valve.VR.SteamVR_Input.p___actions_HandPoseAssist_in_BButtonTouch.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean __actions_HandPoseAssist_in_TriggerTouch
        {
            get
            {
                return Valve.VR.SteamVR_Input.p___actions_HandPoseAssist_in_TriggerTouch.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Single __actions_HandPoseAssist_in_TriggerPull
        {
            get
            {
                return Valve.VR.SteamVR_Input.p___actions_HandPoseAssist_in_TriggerPull.GetCopy <SteamVR_Action_Single>();
            }
        }
        
        public static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[]
            {
                    Valve.VR.SteamVR_Input.__actions_default_in_GrabGrip,
                    Valve.VR.SteamVR_Input.__actions_default_in_Pose,
                    Valve.VR.SteamVR_Input.__actions_default_in_SkeletonLeftHand,
                    Valve.VR.SteamVR_Input.__actions_default_in_SkeletonRightHand,
                    Valve.VR.SteamVR_Input.__actions_default_in_PinchGrip,
                    Valve.VR.SteamVR_Input.__actions_default_out_Haptic,
                    Valve.VR.SteamVR_Input.__actions_HandPoseAssist_in_TrackpadTouch,
                    Valve.VR.SteamVR_Input.__actions_HandPoseAssist_in_AButtonTouch,
                    Valve.VR.SteamVR_Input.__actions_HandPoseAssist_in_BButtonTouch,
                    Valve.VR.SteamVR_Input.__actions_HandPoseAssist_in_TriggerTouch,
                    Valve.VR.SteamVR_Input.__actions_HandPoseAssist_in_TriggerPull};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[]
            {
                    Valve.VR.SteamVR_Input.__actions_default_in_GrabGrip,
                    Valve.VR.SteamVR_Input.__actions_default_in_Pose,
                    Valve.VR.SteamVR_Input.__actions_default_in_SkeletonLeftHand,
                    Valve.VR.SteamVR_Input.__actions_default_in_SkeletonRightHand,
                    Valve.VR.SteamVR_Input.__actions_default_in_PinchGrip,
                    Valve.VR.SteamVR_Input.__actions_HandPoseAssist_in_TrackpadTouch,
                    Valve.VR.SteamVR_Input.__actions_HandPoseAssist_in_AButtonTouch,
                    Valve.VR.SteamVR_Input.__actions_HandPoseAssist_in_BButtonTouch,
                    Valve.VR.SteamVR_Input.__actions_HandPoseAssist_in_TriggerTouch,
                    Valve.VR.SteamVR_Input.__actions_HandPoseAssist_in_TriggerPull};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[]
            {
                    Valve.VR.SteamVR_Input.__actions_default_out_Haptic};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[]
            {
                    Valve.VR.SteamVR_Input.__actions_default_out_Haptic};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[]
            {
                    Valve.VR.SteamVR_Input.__actions_default_in_Pose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[]
            {
                    Valve.VR.SteamVR_Input.__actions_default_in_GrabGrip,
                    Valve.VR.SteamVR_Input.__actions_default_in_PinchGrip,
                    Valve.VR.SteamVR_Input.__actions_HandPoseAssist_in_TrackpadTouch,
                    Valve.VR.SteamVR_Input.__actions_HandPoseAssist_in_AButtonTouch,
                    Valve.VR.SteamVR_Input.__actions_HandPoseAssist_in_BButtonTouch,
                    Valve.VR.SteamVR_Input.__actions_HandPoseAssist_in_TriggerTouch};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[]
            {
                    Valve.VR.SteamVR_Input.__actions_HandPoseAssist_in_TriggerPull};
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[0];
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[]
            {
                    Valve.VR.SteamVR_Input.__actions_default_in_SkeletonLeftHand,
                    Valve.VR.SteamVR_Input.__actions_default_in_SkeletonRightHand};
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[]
            {
                    Valve.VR.SteamVR_Input.__actions_default_in_GrabGrip,
                    Valve.VR.SteamVR_Input.__actions_default_in_PinchGrip,
                    Valve.VR.SteamVR_Input.__actions_HandPoseAssist_in_TrackpadTouch,
                    Valve.VR.SteamVR_Input.__actions_HandPoseAssist_in_AButtonTouch,
                    Valve.VR.SteamVR_Input.__actions_HandPoseAssist_in_BButtonTouch,
                    Valve.VR.SteamVR_Input.__actions_HandPoseAssist_in_TriggerTouch,
                    Valve.VR.SteamVR_Input.__actions_HandPoseAssist_in_TriggerPull};
        }
        
        public static void PreInitActions()
        {
            Valve.VR.SteamVR_Input.p___actions_default_in_GrabGrip = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/default/in/GrabGrip")));
            Valve.VR.SteamVR_Input.p___actions_default_in_Pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create <SteamVR_Action_Pose>("/actions/default/in/Pose")));
            Valve.VR.SteamVR_Input.p___actions_default_in_SkeletonLeftHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create <SteamVR_Action_Skeleton>("/actions/default/in/SkeletonLeftHand")));
            Valve.VR.SteamVR_Input.p___actions_default_in_SkeletonRightHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create <SteamVR_Action_Skeleton>("/actions/default/in/SkeletonRightHand")));
            Valve.VR.SteamVR_Input.p___actions_default_in_PinchGrip = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/default/in/PinchGrip")));
            Valve.VR.SteamVR_Input.p___actions_default_out_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create <SteamVR_Action_Vibration>("/actions/default/out/Haptic")));
            Valve.VR.SteamVR_Input.p___actions_HandPoseAssist_in_TrackpadTouch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/HandPoseAssist/in/TrackpadTouch")));
            Valve.VR.SteamVR_Input.p___actions_HandPoseAssist_in_AButtonTouch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/HandPoseAssist/in/AButtonTouch")));
            Valve.VR.SteamVR_Input.p___actions_HandPoseAssist_in_BButtonTouch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/HandPoseAssist/in/BButtonTouch")));
            Valve.VR.SteamVR_Input.p___actions_HandPoseAssist_in_TriggerTouch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/HandPoseAssist/in/TriggerTouch")));
            Valve.VR.SteamVR_Input.p___actions_HandPoseAssist_in_TriggerPull = ((SteamVR_Action_Single)(SteamVR_Action.Create <SteamVR_Action_Single>("/actions/HandPoseAssist/in/TriggerPull")));
        }
    }
}
