// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_HandPoseAssist : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean TrackpadTouch
        {
            get
            {
                return SteamVR_Actions.handPoseAssist_TrackpadTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean AButtonTouch
        {
            get
            {
                return SteamVR_Actions.handPoseAssist_AButtonTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean BButtonTouch
        {
            get
            {
                return SteamVR_Actions.handPoseAssist_BButtonTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean TriggerTouch
        {
            get
            {
                return SteamVR_Actions.handPoseAssist_TriggerTouch;
            }
        }
        
        public virtual SteamVR_Action_Single TriggerPull
        {
            get
            {
                return SteamVR_Actions.handPoseAssist_TriggerPull;
            }
        }
        
        public virtual SteamVR_Action_Vector2 ThumbHorizontal
        {
            get
            {
                return SteamVR_Actions.handPoseAssist_ThumbHorizontal;
            }
        }
    }
}
