// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean GrabGrip
        {
            get
            {
                return Valve.VR.SteamVR_Input.__actions_default_in_GrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return Valve.VR.SteamVR_Input.__actions_default_in_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return Valve.VR.SteamVR_Input.__actions_default_in_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return Valve.VR.SteamVR_Input.__actions_default_in_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean PinchGrip
        {
            get
            {
                return Valve.VR.SteamVR_Input.__actions_default_in_PinchGrip;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return Valve.VR.SteamVR_Input.__actions_default_out_Haptic;
            }
        }
    }
}
